### PR TITLE
React Unmounter

### PR DESCRIPTION
**Pull request by petejodo**
#### Todo
- [ ] Specs
- [ ] Documentation

### CODE REVIEW

**Comment by antialias** [comment]
I think it would be wise to handle the case where the component's element is moved from one parent node to another. You probably wouldn't want to unmount the component in that case.

**Comment by petejodo** [comment]
hmm interesting. didn't think about that. I'll look into it

**Comment by petejodo** [comment]
So I've come across a couple issues while experimenting on this.

One issue is that we can't reliably unmount components by just attaching a `MutationObserver` to that component's parent. I made a graph to illustrate this...

react-unmounter-1

Not only will MutationObserver not fire for the removal of `el_1`, it also won't fire if the view's element is removed which is the suspected most likely scenario. My current code's implementation is that graph so it's not a good solution.

Now this lead me to an alternate solution which relates to this graph...

react-unmounter-2

The graph is a little incorrect, you wouldn't call `ReactDOM.unmountComponentAtNode(...)`, you would call a supplied `unmount` method that would call `ReactDOM.unmountComponentAtNode(...)` itself but also remove the node from `[ React Elements ]`

This solution has it's own issues. First is that you would have to bind methods to the view's instance much like knockout events works with `bind(this)` so something like...

``` javascript
initialize() {
  // do stuff
  reactUnmounter.register(this);
}

render() {
  // do more stuff
  this.reactMount(someComponent, el); // method was bound to object with call to register
}

someUnrendering() {
  // some stuff
  this.reactUnmount(el);
}
```

This causes the user to do a lot of the management themselves and starting to think that your method of wrapping a react component with a one-off view is a better solution. What do you think @antialias?

**Comment by antialias** [comment]
You could get notified if `el_1` is removed with something like this:

``` js
new MutationObserver(function (mutationRecord) {
  let curNode = myUnmounter.el
  while(curNode = curNode.parentNode) {
    if (curNode === document) {
      // element not removed
      return;
    }
  }
  // element removed;
}).observe(document, {subtree: true});
```

That's going to slow down every mutation on the entire page, so it's not viable. You could scale this in constant-time with respect to the number of unmounters you are using by using one mutationObserver and checking all your currently mounted nodes.

I wouldn't spend too much time on it; I still haven't made anything useful with mutation observers because it's too easy to shoot oneself in the foot with them.

**Comment by antialias** [comment]
this one too

**Comment by petejodo** [comment]
Going to delete this repo since this doesn't seem like a feasible solution as per the above conversation

**Comment by antialias** [comment]
Delete the branch, not the repo!

**Comment by petejodo** [comment]
Well I said that because this PR was the purpose of this repo. I think the view wrapper around a react component seems like the best solution for what we were trying to solve here. We can move that code here and rename this repo accordingly

**Comment by antialias** [comment]
Oh, never-mind, I was thinking this was .com for some reason. Sure delete the repo!

**Pull request closed without merging**
